version: '3.3'
services:

  api:
    build:
      context: .
      dockerfile: ./api.dockerfile
    volumes:
      - .:/usr/src/app
    container_name: 'api-nodejs'
    image: 'api-nodejs'
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - nodenetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'people'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - nodenetwork

networks:
  nodenetwork:
    driver: bridge